### ISSUE TITLE
Typos in tests, rendering them ineffective

### ISSUE THREAD

**Issue by dominikh** [soundcloud/visor#137]
The following tests compare values against themselves instead of the expected values:

```
/src/github.com/soundcloud/visor/runner_test.go:53:5: identical expressions on the left and right side of the '!=' operator
/src/github.com/soundcloud/visor/runner_test.go:56:5: identical expressions on the left and right side of the '!=' operator
/src/github.com/soundcloud/visor/runner_test.go:170:6: identical expressions on the left and right side of the '==' operator
```

**Comment by grobie** [comment]
Thank you for the report. Visor is legacy and I do not recommend using it. We've run into many problems with its implementation and have many lessons learned about some of the design decisions. A few things are mentioned in my talk at KubeCon last year: http://www.slideshare.net/dagrobie/moving-to-kubernetes-tales-from-soundcloud

I recommend looking into modern container management software built upon docker or rkt. At SoundCloud we transitioned to Kubernetes.
