### ISSUE TITLE
Watch out for delete-based events

### ISSUE THREAD

**Issue by cloudhead** [soundcloud/visor#54]
Unsuccessful deletes generate events in doozer, this can be a problem for "unregister" events so either:

a. make sure we don't base events on deletes, but instead on setting files to `""` (they can still be deleted once set)
b. make sure all deletes are going to be successful, ie: check revisions and file existence before issuing a DEL.
c. somehow check that the delete was successful when the event is received, and discard it if not.

**Comment by xla** [comment]
Not relevant anymore. Can be closed.
